// <auto-generated>
//   Auto-generated by Network Storage Sync Tool — DO NOT EDIT.
//   Any changes will be overwritten on next sync.
//
//   To modify, edit the source files in Editor/Network Storage/ and use
//   Editor → Network Storage → Sync Tool to push changes and regenerate.
// </auto-generated>

namespace Sandbox;

/// <summary>
/// Network Storage project configuration — auto-generated from Editor → Network Storage → Sync Tool.
/// The public key (sbox_ns_ prefix) is safe to embed — it is NOT a secret.
/// Runtime settings (e.g. ProxyEnabled) are controlled via Editor → Network Storage → Settings.
/// </summary>
public static class NSConfig
{
	public const string ProjectId = "6c22075ca036481e";
	public const string PublicKey = "sbox_ns_51855ba40d8642b185543f8c5c031cc2";
	public const string BaseUrl = "https://api.sboxcool.com";
	public const string ApiVersion = "v3";
	public const string PublishTarget = "live";

	/// <summary>
	/// Whether the game host proxies Network Storage API calls for non-host clients.
	/// Enable for editor/local testing. Disable in production when every player has their own Steam account.
	/// Controlled via Editor → Network Storage → Settings.
	/// </summary>
	public const bool ProxyEnabled = false;

	/// <summary>Whether this project is configured to use fast auth sessions.</summary>
	public const bool EnableAuthSessions = false;

	/// <summary>Whether this project is configured to send encrypted Network Storage requests.</summary>
	public const bool EnableEncryptedRequests = false;

	/// <summary>Configure the NetworkStorage runtime client. Delegates to NetworkStorage.EnsureConfigured().</summary>
	public static void EnsureConfigured() => NetworkStorage.EnsureConfigured();
}
