// <auto-generated>
//   Auto-generated by Network Storage Sync Tool — DO NOT EDIT.
//   Any changes will be overwritten on next sync.
//
//   To modify, edit the source files in Editor/Network Storage/ and use
//   Editor → Network Storage → Sync Tool to push changes and regenerate.
// </auto-generated>

namespace Sandbox;

/// <summary>
/// Network Storage endpoint slugs.
/// Use these constants with NetworkStorage.CallEndpoint() instead of raw strings.
/// </summary>
public static class NSEndpoints
{
	/// <summary>Create the first-time player row across all 8 collections with default values | Method: POST</summary>
	public const string InitPlayer = "init-player";

	/// <summary>Returns the global leaderboard record containing every player's summary entry | Method: GET</summary>
	public const string Leaderboard = "leaderboard";

	/// <summary>Reads all 8 collections and returns the merged player state | Method: GET</summary>
	public const string LoadPlayer = "load-player";

	/// <summary>Writes every collection in one atomic call. Guards against regression overwrites: refuses to lower totalLevel, totalKills, or nodesMined. Used for autosave and logout. | Method: POST</summary>
	public const string SaveAll = "save-all";

	/// <summary>Writes the bank stackables and bank unique items collections | Method: POST</summary>
	public const string SaveBank = "save-bank";

	/// <summary>Writes the inventory slots and equipment state in one call | Method: POST</summary>
	public const string SaveInventory = "save-inventory";

	/// <summary>Writes the per-monster kill counts | Method: POST</summary>
	public const string SaveKills = "save-kills";

	/// <summary>Writes recipes, stones, quests, spells, and chest claim data | Method: POST</summary>
	public const string SaveProgression = "save-progression";

	/// <summary>Writes the skills collection (level/xp per skill) | Method: POST</summary>
	public const string SaveSkills = "save-skills";

	/// <summary>Writes the players collection fields and updates the global leaderboard entry for this player | Method: POST</summary>
	public const string SaveStats = "save-stats";

	/// <summary>Input field keys for endpoints that accept POST data.</summary>
	public static class Input
	{
		/// <summary>Initialize Player input fields.</summary>
		public static class InitPlayer
		{
			/// <summary>Type: string</summary>
			public const string PlayerName = "playerName";
		}

		/// <summary>Save All input fields.</summary>
		public static class SaveAll
		{
			/// <summary>Type: object</summary>
			public const string BankStackables = "bankStackables";
			/// <summary>Type: array (unknown)</summary>
			public const string BankUnique = "bankUnique";
			/// <summary>Type: object</summary>
			public const string ChestClaims = "chestClaims";
			/// <summary>Type: number</summary>
			public const string Currency = "currency";
			/// <summary>Type: number</summary>
			public const string CurrentMana = "currentMana";
			/// <summary>Type: array (unknown)</summary>
			public const string DiscoveredQuests = "discoveredQuests";
			/// <summary>Type: object</summary>
			public const string Equipped = "equipped";
			/// <summary>Type: string</summary>
			public const string EquippedAmmoId = "equippedAmmoId";
			/// <summary>Type: number</summary>
			public const string EquippedAmmoQty = "equippedAmmoQty";
			/// <summary>Type: number</summary>
			public const string EquippedAmmoSlotIndex = "equippedAmmoSlotIndex";
			/// <summary>Type: object</summary>
			public const string EquippedSlotIndices = "equippedSlotIndices";
			/// <summary>Type: number</summary>
			public const string InventoryExpansions = "inventoryExpansions";
			/// <summary>Type: object</summary>
			public const string Kills = "kills";
			/// <summary>Type: number</summary>
			public const string NodesMined = "nodesMined";
			/// <summary>Type: string</summary>
			public const string PlayerName = "playerName";
			/// <summary>Type: array (unknown)</summary>
			public const string Quests = "quests";
			/// <summary>Type: array (unknown)</summary>
			public const string Recipes = "recipes";
			/// <summary>Type: string</summary>
			public const string SavedAt = "savedAt";
			/// <summary>Type: object</summary>
			public const string Skills = "skills";
			/// <summary>Type: array (unknown)</summary>
			public const string Slots = "slots";
			/// <summary>Type: array (unknown)</summary>
			public const string Stones = "stones";
			/// <summary>Type: number</summary>
			public const string TotalGold = "totalGold";
			/// <summary>Type: number</summary>
			public const string TotalKills = "totalKills";
			/// <summary>Type: number</summary>
			public const string TotalLevel = "totalLevel";
			/// <summary>Type: array (unknown)</summary>
			public const string UnlockedSpells = "unlockedSpells";
		}

		/// <summary>Save Bank input fields.</summary>
		public static class SaveBank
		{
			/// <summary>Type: array (unknown)</summary>
			public const string Items = "items";
			/// <summary>Type: object</summary>
			public const string Stackables = "stackables";
		}

		/// <summary>Save Inventory input fields.</summary>
		public static class SaveInventory
		{
			/// <summary>Type: object</summary>
			public const string Equipped = "equipped";
			/// <summary>Type: object</summary>
			public const string EquippedSlotIndices = "equippedSlotIndices";
			/// <summary>Type: array (unknown)</summary>
			public const string Slots = "slots";
		}

		/// <summary>Save Kills input fields.</summary>
		public static class SaveKills
		{
			/// <summary>Type: object (required)</summary>
			public const string Counts = "counts";
		}

		/// <summary>Save Progression input fields.</summary>
		public static class SaveProgression
		{
			/// <summary>Type: object</summary>
			public const string ChestClaims = "chestClaims";
			/// <summary>Type: array (unknown)</summary>
			public const string DiscoveredQuests = "discoveredQuests";
			/// <summary>Type: array (unknown)</summary>
			public const string Quests = "quests";
			/// <summary>Type: array (unknown)</summary>
			public const string Recipes = "recipes";
			/// <summary>Type: array (unknown)</summary>
			public const string Stones = "stones";
			/// <summary>Type: array (unknown)</summary>
			public const string UnlockedSpells = "unlockedSpells";
		}

		/// <summary>Save Skills input fields.</summary>
		public static class SaveSkills
		{
			/// <summary>Type: object (required)</summary>
			public const string Entries = "entries";
		}

		/// <summary>Save Stats input fields.</summary>
		public static class SaveStats
		{
			/// <summary>Type: number</summary>
			public const string Currency = "currency";
			/// <summary>Type: number</summary>
			public const string CurrentMana = "currentMana";
			/// <summary>Type: string</summary>
			public const string EquippedAmmoId = "equippedAmmoId";
			/// <summary>Type: number</summary>
			public const string EquippedAmmoQty = "equippedAmmoQty";
			/// <summary>Type: number</summary>
			public const string EquippedAmmoSlotIndex = "equippedAmmoSlotIndex";
			/// <summary>Type: number</summary>
			public const string InventoryExpansions = "inventoryExpansions";
			/// <summary>Type: number</summary>
			public const string NodesMined = "nodesMined";
			/// <summary>Type: string</summary>
			public const string PlayerName = "playerName";
			/// <summary>Type: string</summary>
			public const string SavedAt = "savedAt";
			/// <summary>Type: number</summary>
			public const string TotalGold = "totalGold";
			/// <summary>Type: number</summary>
			public const string TotalKills = "totalKills";
			/// <summary>Type: number</summary>
			public const string TotalLevel = "totalLevel";
		}
	}
}
